// <auto-generated />
using System;
using CrmBrusnika.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CrmBrusnika.Migrations.ObjectEntities
{
    [DbContext(typeof(ObjectEntitiesContext))]
    [Migration("20231229015843_AddObjectEntities")]
    partial class AddObjectEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CrmBrusnika.Models.ObjectEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvailabilityEngineeringNetworks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GeotechnicalConditions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("JuridicalCost")
                        .HasColumnType("double precision");

                    b.Property<string>("PermissiveSide")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TransportationaAccessibility")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ObjectEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
