version: '3.4'

services:
  backend:
    image: crm-backend
    depends_on:
      - postgres
    restart: always
    ports:
      - 5000:80

  postgres:
    container_name: postgres
    image: postgres
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jo31fMLj0YfC1xa
      #POSTGRES_DB: crm-brusnika
      #POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 6969:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=obuhowdaniil902@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=jo31fMLj0YfC1xa
    ports:
      - 5050:80

  client:
    image: crm-frontend
    ports:
      -  3000:3000

  proxy:
    image: nginx:mainline
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
        - "80:80"  

    
volumes:
 pgdata:
